name: Deploy Blue-Green Remedial

on:
  push:
    branches: [ "main" ]

jobs:
  # ETAPA 1: Compilación y Pruebas de .NET
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run .NET Unit Tests
        run: dotnet test --configuration Release --no-restore

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/owen-nos-abandono/remedial:latest

  # ETAPA 2: Despliegue Blue-Green
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Execute Blue-Green Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_DOCKER_SERVER_IP }}
          username: riveradiazjanine
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "$(docker ps -q -f name=app-blue)" ]; then
              NEW_COLOR="green"
              NEW_PORT="8081"
              OLD_COLOR="blue"
            else
              NEW_COLOR="blue"
              NEW_PORT="8080"
              OLD_COLOR="green"
            fi

            echo "Desplegando versión $NEW_COLOR en puerto $NEW_PORT..."

            docker pull ghcr.io/owen-nos-abandono/remedial:latest
            docker stop app-$NEW_COLOR || true
            docker rm app-$NEW_COLOR || true

            docker run -d --name app-$NEW_COLOR -p $NEW_PORT:8080 \
              --restart always \
              ghcr.io/owen-nos-abandono/remedial:latest

            sleep 15

            # Cambio de tráfico en Nginx (VM 10.0.2.3)
            ssh -o StrictHostKeyChecking=no riveradiazjanine@10.0.2.3 \
            "sudo sed -i 's/server 10.0.1.2:.*/server 10.0.1.2:$NEW_PORT;/' /etc/nginx/sites-available/default && sudo systemctl reload nginx"

            # Limpieza automática
            docker stop app-$OLD_COLOR || true
            docker rm app-$OLD_COLOR || true
            docker image prune -af

  # ETAPA 3: Prueba de Carga con K6
  performance-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run K6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6-script.js
          flags: --vus 5 --duration 20s