name: Deploy Blue-Green Remedial

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Esto soluciona el error de permisos que tenías
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos el nombre de tu paquete actual
          tags: ghcr.io/owen-nos-abandono/remedial:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_DOCKER_SERVER_IP }}
          username: riveradiazjanine
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            # Detectar color
            if [ "$(docker ps -q -f name=app-blue)" ]; then
              NEW_COLOR="green"
              NEW_PORT="8081"
              OLD_COLOR="blue"
            else
              NEW_COLOR="blue"
              NEW_PORT="8080"
              OLD_COLOR="green"
            fi

            # Bajar imagen nueva
            docker pull ghcr.io/owen-nos-abandono/remedial:latest

            # Limpiar el que está en bucle o fallando
            docker stop app-$NEW_COLOR || true
            docker rm app-$NEW_COLOR || true

            # Correr nuevo contenedor con la conexión a la base de datos
            docker run -d --name app-$NEW_COLOR \
              -p $NEW_PORT:8080 \
              -e CONNECTION_STRING="${{ secrets.DB_CONNECTION }}" \
              --restart always \
              ghcr.io/owen-nos-abandono/remedial:latest

            sleep 15
            
            # Cambiar tráfico en Nginx (VM 10.0.2.3)
            ssh -o StrictHostKeyChecking=no riveradiazjanine@10.0.2.3 \
            "sudo sed -i 's/server 10.0.1.2:.*/server 10.0.1.2:$NEW_PORT;/' /etc/nginx/sites-available/default && sudo systemctl reload nginx"

            # Borrar el viejo
            docker stop app-$OLD_COLOR || true
            docker rm app-$OLD_COLOR || true